# Generated by Django 4.2.5 on 2023-09-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reserve',
            new_name='Menu',
        ),
    ]
