# Generated by Django 4.2.5 on 2023-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_rename_reserve_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
